---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://gitgitcode.github.io"
title: "Hugo Blog Template for GitHub Pages"
canonifyurls: true
theme: "ananke"
...